### ISSUE TITLE
Request on Instructions to Run the Code

### ISSUE THREAD

**Issue by night-chen** [alisawuffles/proxy-tuning#1]
Hi Alisa,

Thank you for the open-sourcing data and code of your great work! I am wondering whether you can provide a more detailed instruction on how to run the code in this repository, like which script to run first and the data structure under the directory `./data/`. That can help us a lot. 

Many thanks again!

**Comment by alisawuffles** [comment]
Hi there! All of the evaluation scripts are provided in `scripts/`. Over the coming week, I will improve the documentation of the repository, including for the `data/` folder. If you have any specific questions in the meantime, please feel free to ask!

**Comment by alisawuffles** [comment]
Hi there! I uploaded a zip folder (`data.zip`) with our evaluation data, and cleaned up the scripts in `scripts/eval`, which contain examples of how to evaluate every model on every dataset. Please let me know if you have any further questions!

**Comment by night-chen** [comment]
Thank you so much for the timely response! That would be of great help! I really like the inspiring work.
