### ISSUE TITLE
About the requirements of computational resources for finetuning llama2 models

### ISSUE THREAD

**Issue by hyy-2000** [alisawuffles/proxy-tuning#2]
Hi Alisa! Thank you for your inspiring work and code.
When I was trying to reproduce the finetuning results of llama2 7B/13B model, I encountered the problem of running out of GPU memory. I was using 4 A100s(40GB) with 4*40GB of GPU memory. According to your paper, you also used 4 A100s for tuning said models, so I'm just trying to figure out is it that you used 4 A100s(80GB) with 4*80 GB of GPU memory, or other problems occured during the process. Thank you for your time!

**Comment by alisawuffles** [comment]
Hi there, thanks for the question! Your guess was correct, we have 80G A100s. We’ll be sure to update the preprint to include this detail!

**Comment by hyy-2000** [comment]
Thanks a lot!
