### ISSUE TITLE
About the training data of AlpacaFarm, ToxiGen, TruthfulQA, CodexEval and DS-1000

### ISSUE THREAD

**Issue by 1170300714** [alisawuffles/proxy-tuning#4]
Hi,
Thanks for your great job!
Could you please share the training data of AlpacaFarm, ToxiGen, TruthfulQA, CodexEval and DS-1000? In fact, I can only find the training 
 data of GSM and TriviaQA in [https://github.com/alisawuffles/proxy-tuning/issues/3](url).

Thanks a lot!

**Comment by 1170300714** [comment]
In addition, what is the different between ''Instruction-Tuning'' ,  "Code Adaptation"  and ''Task Finetuning" in terms of training paradigm? In practice, I have reproduce the ''Task Finetuning'' in your paper by the open_instruct/finetune.py which you released.  For Instruction-Tuning and Code Adaptation, which corresponding training code should I run to start the experiment?

Thanks a lot~

**Comment by chunmeifeng** [comment]
Hi author, I also need the training data of AlpacaFarm, ToxiGen, TruthfulQA, CodexEval and DS-1000, could you please share with this?

**Comment by 1170300714** [comment]
收到，感谢您的来件

**Comment by alisawuffles** [comment]
**We do not use training data for any of the tasks you listed.** For instruction-tuning and code adaptation experiments, **we use off-the-shelf models** (in other words, we did not do any training ourselves). Moreover, the experts are supposed to be general-purpose instruction-following and code models, respectively — they are not task specific.

For the instruction-tuning experiments, for the expert we use a _general_ instruction-tuned model from the Llama2 chat series, which you can find here on [HuggingFace models](https://huggingface.co/collections/meta-llama/llama-2-family-661da1f90a9d678b6f55773b). For code adaptation experiments, we use a _general_ code model, the CodeLlama series, [here](https://huggingface.co/collections/meta-llama/code-llama-family-661da32d0a9d678b6f55b933). You can see how to do evaluation in the [eval scripts](https://github.com/alisawuffles/proxy-tuning/tree/main/scripts/eval).

The three sections evaluate three common use cases of tuning: instruction-tuning, domain adaptation, and task-specific finetuning. The expert model for each section is chosen accordingly.

**Comment by 1170300714** [comment]
Thanks for your reply!
