### ISSUE TITLE
Data for finetuning

### ISSUE THREAD

**Issue by hstko** [alisawuffles/proxy-tuning#6]
How can I obtain the training data for finetuning the GSM task?
I downloaded the official GSM train jsonl and set the path, but I received a message that the format is incorrect.
If a conversion is necessary, please let me know how to do it.
https://github.com/openai/grade-school-math/tree/master/grade_school_math/data

**Comment by alisawuffles** [comment]
Hi there! Sorry for the delayed response. This [data](https://drive.google.com/file/d/1Tj805xgskovNztI3ECZcaXw0ydAZDSs6/view?usp=drive_link) folder contains the processed training data for GSM and TriviaQA.

**Comment by hstko** [comment]
Thank you!
